# core.yaml - Core Service Configuration
service_name: "core-service"

discovery:
  # Service discovery filter (label-based selection)
  filter:
    labels:
      - app.goletan.discover: "true"

orchestrator:
  # Orchestration strategy (serial|parallel|hybrid)
  strategy: "hybrid"

  # Static priority map (overrides dynamic priorities when present)
  priority_map:
    events-service: 10       # High priority service
    core-service: 20

  # Tag name to check for dynamic priority (empty = disabled)
  priority_tag: "service_priority"

  # Default priority when no other priority is found
  default_priority: 99